---
JAPAN:
  rootDir: "JAPAN/SAST"
  product_git_url: "https://api.github.com/repos/lemonfisk/JAPAN"
  components:
    - name: YOKO
      params:
        git_url: "git@github.com:lemonfisk/YOKO.git"
        ptai_language: "Python"

    - name: FUDZI
      params:
        git_url: "git@github.com:lemonfisk/FUDZI.git"
        ptai_language: "Python"

    - name: TOKIO
      params:
        git_url: "https://api.github.com/repos/lemonfisk/TOKIO"
        ptai_language: "Java"
        ptai_jdk_version: "11"


    - name: PREFECTURA
      depend_on: TOKIO
      params:
        git_url: "git@github.com:lemonfisk/PREFECTURA.git"
        ptai_language: "Java"
        ptai_jdk_version: "17"

    - name: MERLIN
      depend_on: TOKIO
      params:
        git_url: "git@github.com:lemonfisk/MERLIN.git"
        ptai_language: "JavaTERSA"
        ptai_jdk_version: "48"

CHINA:
  rootDir: "CHINA/SAST"
  product_git_url: "https://api.github.com/repos/lemonfisk/CHINA"
  components:
    - name: PEKIN
      params:
        git_url: "git@github.com:lemonfisk/PEKIN.git"
        ptai_language: "JavaScript"

#RUSSIA:
#  rootDir: "RUSSIA/SAST"
#  product_git_url: "https://api.github.com/repos/lemonfisk/RUSSIA"
#  components:
#    - name: RUSSIA
#      params:
#        project_git_branch: "develop/3.7.1"
#        ptai_language: "Python"